"""Backend-only text-to-speech proxy.

The browser never receives the ElevenLabs credential. Voice IDs are configured
per environment because voice availability is account-specific, especially for
Darija. If TTS is not configured, callers can use browser SpeechSynthesis.
"""

import logging
from typing import Optional

import httpx

from app.core.config import settings

logger = logging.getLogger(__name__)

_VOICE_SETTING_BY_LANGUAGE = {
    "fr": "TTS_VOICE_FR",
    "darija": "TTS_VOICE_DARIJA",
    "ar": "TTS_VOICE_AR",
    "en": "TTS_VOICE_EN",
}
_LANGUAGE_BY_CODE = {"fr": "fr", "darija": "darija", "ar": "ar", "en": "en"}


def normalize_language(language: str | None) -> str:
    value = (language or "fr").lower().strip()
    if value in _LANGUAGE_BY_CODE:
        return value
    if value.startswith("fr"):
        return "fr"
    if value.startswith("ar"):
        return "ar"
    if value.startswith("en"):
        return "en"
    return "fr"


async def synthesize_speech(text: str, language: str | None) -> Optional[bytes]:
    """Return MP3 bytes when a configured server-side provider is available."""
    normalized = normalize_language(language)
    voice_setting = _VOICE_SETTING_BY_LANGUAGE[normalized]
    voice_id = getattr(settings, voice_setting, "")
    api_key = settings.ELEVENLABS_API_KEY
    if not api_key or not voice_id:
        return None

    # The text was generated by our assistant and remains bounded by the route.
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
    headers = {"xi-api-key": api_key, "Content-Type": "application/json", "Accept": "audio/mpeg"}
    payload = {
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }
    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            response = await client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            return response.content
    except Exception:
        logger.exception("TTS provider request failed")
        return None
