export interface BrandInfo {
  name: string;
  slug: string;
  logo: string;
  country: string;
  flag: string;
}

export const POPULAR_BRANDS: BrandInfo[] = [
  { name: "Abarth", slug: "abarth", logo: "/logos/abarth.png", country: "Italie", flag: "🇮🇹" },
  { name: "Alfa Romeo", slug: "alfa-romeo", logo: "/logos/alfaromeo.png", country: "Italie", flag: "🇮🇹" },
  { name: "Alpine", slug: "alpine", logo: "/logos/alpine.png", country: "France", flag: "🇫🇷" },
  { name: "Aston Martin", slug: "aston-martin", logo: "/logos/astonmartin.png", country: "Royaume-Uni", flag: "🇬🇧" },
  { name: "Audi", slug: "audi", logo: "/logos/audi.png", country: "Allemagne", flag: "🇩🇪" },
  { name: "BAIC", slug: "baic", logo: "/logos/baic.png", country: "Chine", flag: "🇨🇳" },
  { name: "Bentley", slug: "bentley", logo: "/logos/bentley.png", country: "Royaume-Uni", flag: "🇬🇧" },
  { name: "BMW", slug: "bmw", logo: "/logos/bmw.png", country: "Allemagne", flag: "🇩🇪" },
  { name: "BYD", slug: "byd", logo: "/logos/byd.png", country: "Chine", flag: "🇨🇳" },
  { name: "Changan", slug: "changan", logo: "/logos/changan.png", country: "Chine", flag: "🇨🇳" },
  { name: "Chery", slug: "chery", logo: "/logos/chery.png", country: "Chine", flag: "🇨🇳" },
  { name: "Citroën", slug: "citroen", logo: "/logos/citroen.png", country: "France", flag: "🇫🇷" },
  { name: "Cupra", slug: "cupra", logo: "/logos/cupra.png", country: "Espagne", flag: "🇪🇸" },
  { name: "Dacia", slug: "dacia", logo: "/logos/dacia.png", country: "France / Roumanie", flag: "🇫🇷" },
  { name: "Deepal", slug: "deepal", logo: "/logos/deepal.png", country: "Chine", flag: "🇨🇳" },
  { name: "DFSK", slug: "dfsk", logo: "/logos/dfsk.png", country: "Chine", flag: "🇨🇳" },
  { name: "Dongfeng", slug: "dongfeng", logo: "/logos/dongfeng.png", country: "Chine", flag: "🇨🇳" },
  { name: "DS Automobiles", slug: "ds-automobiles", logo: "/logos/ds.png", country: "France", flag: "🇫🇷" },
  { name: "Exeed", slug: "exeed", logo: "/logos/exeed.png", country: "Chine", flag: "🇨🇳" },
  { name: "Ferrari", slug: "ferrari", logo: "/logos/ferrari.png", country: "Italie", flag: "🇮🇹" },
  { name: "Fiat", slug: "fiat", logo: "/logos/fiat.png", country: "Italie", flag: "🇮🇹" },
  { name: "Ford", slug: "ford", logo: "/logos/ford.png", country: "USA", flag: "🇺🇸" },
  { name: "GAC", slug: "gac", logo: "/logos/gac.png", country: "Chine", flag: "🇨🇳" },
  { name: "Geely", slug: "geely", logo: "/logos/geely.png", country: "Chine", flag: "🇨🇳" },
  { name: "GWM", slug: "gwm", logo: "/logos/gwm.png", country: "Chine", flag: "🇨🇳" },
  { name: "Honda", slug: "honda", logo: "/logos/honda.png", country: "Japon", flag: "🇯🇵" },
  { name: "Hyundai", slug: "hyundai", logo: "/logos/hyundai.png", country: "Corée du Sud", flag: "🇰🇷" },
  { name: "Isuzu", slug: "isuzu", logo: "/logos/isuzu.png", country: "Japon", flag: "🇯🇵" },
  { name: "JAC", slug: "jac", logo: "/logos/jac.png", country: "Chine", flag: "🇨🇳" },
  { name: "Jaecoo", slug: "jaecoo", logo: "/logos/jaecoo.png", country: "Chine", flag: "🇨🇳" },
  { name: "Jaguar", slug: "jaguar", logo: "/logos/jaguar.png", country: "Royaume-Uni", flag: "🇬🇧" },
  { name: "Jeep", slug: "jeep", logo: "/logos/jeep.png", country: "USA", flag: "🇺🇸" },
  { name: "Jetour", slug: "jetour", logo: "/logos/jetour.png", country: "Chine", flag: "🇨🇳" },
  { name: "KG Mobility", slug: "kg-mobility", logo: "/logos/kgm.png", country: "Corée du Sud", flag: "🇰🇷" },
  { name: "Kia", slug: "kia", logo: "/logos/kia.png", country: "Corée du Sud", flag: "🇰🇷" },
  { name: "Land Rover", slug: "land-rover", logo: "/logos/landrover.png", country: "Royaume-Uni", flag: "🇬🇧" },
  { name: "Leapmotor", slug: "leapmotor", logo: "/logos/leapmotor.png", country: "Chine", flag: "🇨🇳" },
  { name: "Lexus", slug: "lexus", logo: "/logos/lexus.png", country: "Japon", flag: "🇯🇵" },
  { name: "Lotus", slug: "lotus", logo: "/logos/lotus.png", country: "Royaume-Uni", flag: "🇬🇧" },
  { name: "Lynk & Co", slug: "lynk-co", logo: "/logos/lynkco.png", country: "Chine", flag: "🇨🇳" },
  { name: "Mahindra", slug: "mahindra", logo: "/logos/mahindra.png", country: "Inde", flag: "🇮🇳" },
  { name: "Maserati", slug: "maserati", logo: "/logos/maserati.png", country: "Italie", flag: "🇮🇹" },
  { name: "Mazda", slug: "mazda", logo: "/logos/mazda.png", country: "Japon", flag: "🇯🇵" },
  { name: "Mercedes-Benz", slug: "mercedes-benz", logo: "/logos/mercedes.png", country: "Allemagne", flag: "🇩🇪" },
  { name: "MG", slug: "mg", logo: "/logos/mg.png", country: "Royaume-Uni / Chine", flag: "🇬🇧" },
  { name: "Mini", slug: "mini", logo: "/logos/mini.png", country: "Royaume-Uni", flag: "🇬🇧" },
  { name: "Mitsubishi", slug: "mitsubishi", logo: "/logos/mitsubishi.png", country: "Japon", flag: "🇯🇵" },
  { name: "Nissan", slug: "nissan", logo: "/logos/nissan.png", country: "Japon", flag: "🇯🇵" },
  { name: "Omoda", slug: "omoda", logo: "/logos/omoda.png", country: "Chine", flag: "🇨🇳" },
  { name: "Opel", slug: "opel", logo: "/logos/opel.png", country: "Allemagne", flag: "🇩🇪" },
  { name: "Peugeot", slug: "peugeot", logo: "/logos/peugeot.png", country: "France", flag: "🇫🇷" },
  { name: "Porsche", slug: "porsche", logo: "/logos/porsche.png", country: "Allemagne", flag: "🇩🇪" },
  { name: "Renault", slug: "renault", logo: "/logos/renault.png", country: "France", flag: "🇫🇷" },
  { name: "Rox", slug: "rox", logo: "/logos/rox.png", country: "Chine", flag: "🇨🇳" },
  { name: "Seat", slug: "seat", logo: "/logos/seat.png", country: "Espagne", flag: "🇪🇸" },
  { name: "Seres", slug: "seres", logo: "/logos/seres.png", country: "Chine", flag: "🇨🇳" },
  { name: "Skoda", slug: "skoda", logo: "/logos/skoda.png", country: "Rép. Tchèque", flag: "🇨🇿" },
  { name: "Smart", slug: "smart", logo: "/logos/smart.png", country: "Allemagne", flag: "🇩🇪" },
  { name: "Soueast", slug: "soueast", logo: "/logos/soueast.png", country: "Chine", flag: "🇨🇳" },
  { name: "Suzuki", slug: "suzuki", logo: "/logos/suzuki.png", country: "Japon", flag: "🇯🇵" },
  { name: "Tesla", slug: "tesla", logo: "/logos/tesla.png", country: "USA", flag: "🇺🇸" },
  { name: "Toyota", slug: "toyota", logo: "/logos/toyota.png", country: "Japon", flag: "🇯🇵" },
  { name: "Volkswagen", slug: "volkswagen", logo: "/logos/volkswagen.png", country: "Allemagne", flag: "🇩🇪" },
  { name: "Volvo", slug: "volvo", logo: "/logos/volvo.png", country: "Suède", flag: "🇸🇪" },
  { name: "Xpeng", slug: "xpeng", logo: "/logos/xpeng.png", country: "Chine", flag: "🇨🇳" },
  { name: "Zeekr", slug: "zeekr", logo: "/logos/zeekr.png", country: "Chine", flag: "🇨🇳" },
];
