export const POPULAR_BRANDS = [
  { name: "Dacia", logo: "/logos/dacia.png" },
  { name: "Renault", logo: "/logos/renault.png" },
  { name: "Peugeot", logo: "/logos/peugeot.png" },
  { name: "Hyundai", logo: "/logos/hyundai.png" },
  { name: "Volkswagen", logo: "/logos/volkswagen.png" },
  { name: "Fiat", logo: "/logos/fiat.png" },
  { name: "Citroën", logo: "/logos/citroen.png" },
  { name: "Ford", logo: "/logos/ford.png" },
  { name: "Kia", logo: "/logos/kia.png" },
  { name: "Toyota", logo: "/logos/toyota.png" },
  { name: "Audi", logo: "/logos/audi.png" },
  { name: "BMW", logo: "/logos/bmw.png" },
  { name: "Mercedes-Benz", logo: "/logos/mercedes.png" },
  { name: "Jeep", logo: "/logos/jeep.png" },
  { name: "Nissan", logo: "/logos/nissan.png" },
  { name: "Skoda", logo: "/logos/skoda.png" },
  { name: "Seat", logo: "/logos/seat.png" },
  { name: "Opel", logo: "/logos/opel.png" },
  { name: "Honda", logo: "/logos/honda.png" },
  { name: "Volvo", logo: "/logos/volvo.png" },
  { name: "Land Rover", logo: "/logos/landrover.png" },
  { name: "Alfa Romeo", logo: "/logos/alfaromeo.png" },
  { name: "Porsche", logo: "/logos/porsche.png" },
  { name: "Suzuki", logo: "/logos/suzuki.png" },
  { name: "BYD", logo: "/logos/byd.png" },
  { name: "MG", logo: "/logos/mg.png" },
  { name: "Chery", logo: "/logos/chery.png" },
  { name: "Geely", logo: "/logos/geely.png" },
  { name: "Changan", logo: "/logos/changan.png" },
  { name: "Dongfeng", logo: "/logos/dongfeng.png" },
  { name: "Haval", logo: "/logos/haval.png" },
  { name: "JAC", logo: "/logos/jac.png" },
  { name: "Mazda", logo: "/logos/mazda.png" },
  { name: "Mitsubishi", logo: "/logos/mitsubishi.png" },
  { name: "Mini", logo: "/logos/mini.png" },
  { name: "Lexus", logo: "/logos/lexus.png" },
  { name: "Jaguar", logo: "/logos/jaguar.png" },
  { name: "Maserati", logo: "/logos/maserati.png" },
  { name: "Cupra", logo: "/logos/cupra.png" },
  { name: "DS", logo: "/logos/ds.png" },
  { name: "Omoda", logo: "/logos/omoda.png" },
  { name: "Jaecoo", logo: "/logos/jaecoo.png" },
  { name: "BAIC", logo: "/logos/baic.png" },
  { name: "Seres", logo: "/logos/seres.png" },
  { name: "DFSK", logo: "/logos/dfsk.png" }
];
