export const POPULAR_BRANDS = [
  { name: "Dacia", logo: "https://www.wandaloo.com/imgs/logo-DACIA.png" },
  { name: "Renault", logo: "https://www.wandaloo.com/imgs/logo-Renault-b.png" },
  { name: "Peugeot", logo: "https://www.wandaloo.com/imgs/logo-Peugeot-b.png" },
  { name: "Hyundai", logo: "https://www.wandaloo.com/imgs/logo-Hyundai-b.png" },
  { name: "Volkswagen", logo: "https://www.wandaloo.com/imgs/logo-Volkswagen-b.png" },
  { name: "Fiat", logo: "https://www.wandaloo.com/imgs/logo-Fiat-b.png" },
  { name: "Citroën", logo: "https://www.wandaloo.com/imgs/logo-Citroen-b.png" },
  { name: "Ford", logo: "https://www.wandaloo.com/imgs/logo-Ford-b.png" },
  { name: "Kia", logo: "https://www.wandaloo.com/imgs/logo-Kia-b.png" },
  { name: "Toyota", logo: "https://www.wandaloo.com/imgs/logo-Toyota-b.png" },
  { name: "Audi", logo: "https://www.wandaloo.com/imgs/logo-Audi-b.png" },
  { name: "BMW", logo: "https://www.wandaloo.com/imgs/logo-BMW-b.png" },
  { name: "Mercedes-Benz", logo: "https://www.wandaloo.com/imgs/logo-Mercedes-b.png" },
  { name: "Jeep", logo: "https://www.wandaloo.com/imgs/logo-Jeep-b.png" },
  { name: "Nissan", logo: "https://www.wandaloo.com/imgs/logo-Nissan-b.png" },
  { name: "Skoda", logo: "https://www.wandaloo.com/imgs/logo-SKODA.png" },
  { name: "Seat", logo: "https://www.wandaloo.com/imgs/logo-Seat-b.png" },
  { name: "Opel", logo: "https://www.wandaloo.com/imgs/logo-Opel-b.png" },
  { name: "Honda", logo: "https://www.wandaloo.com/imgs/logo-Honda-b.png" },
  { name: "Volvo", logo: "https://www.wandaloo.com/imgs/logo-Volvo-b.png" },
  { name: "Land Rover", logo: "https://www.wandaloo.com/imgs/logo-LandRover-b.png" },
  { name: "Alfa Romeo", logo: "https://www.wandaloo.com/imgs/logo-ALFA-ROMEO.png" },
  { name: "Porsche", logo: "https://www.wandaloo.com/imgs/logo-Porsche-b.png" },
  { name: "Suzuki", logo: "https://www.wandaloo.com/imgs/logo-Suzuki-b.png" },
  { name: "BYD", logo: "https://www.wandaloo.com/imgs/logo-BYD.png" },
  { name: "MG", logo: "https://www.wandaloo.com/imgs/logo-MG-b.png" },
  { name: "Chery", logo: "https://www.wandaloo.com/imgs/logo-CHERY.png" },
  { name: "Geely", logo: "https://www.wandaloo.com/imgs/logo-Geely-b.png" },
  { name: "Changan", logo: "https://www.wandaloo.com/imgs/logo-Changan.png" },
  { name: "Dongfeng", logo: "https://www.wandaloo.com/imgs/logo-DONGFENG.png" },
  { name: "Haval", logo: "https://www.wandaloo.com/imgs/logo-GWM.png" },
  { name: "JAC", logo: "https://www.wandaloo.com/imgs/logo-JAC.png" },
  { name: "Mazda", logo: "https://www.wandaloo.com/imgs/logo-Mazda-b.png" },
  { name: "Mitsubishi", logo: "https://www.wandaloo.com/imgs/logo-Mitsubishi-b.png" },
  { name: "Mini", logo: "https://www.wandaloo.com/imgs/logo-MINI-b.png" },
  { name: "Lexus", logo: "https://www.wandaloo.com/imgs/logo-Lexus-b.png" },
  { name: "Jaguar", logo: "https://www.wandaloo.com/imgs/logo-Jaguar-b.png" },
  { name: "Maserati", logo: "https://www.wandaloo.com/imgs/logo-Maserati-b.png" },
  { name: "BAIC", logo: "https://www.wandaloo.com/imgs/logo-BAIC-Motor.png" },
  { name: "Seres", logo: "https://www.wandaloo.com/imgs/logo-Seres-b.png" },
  { name: "Omoda", logo: "https://www.wandaloo.com/imgs/logo-OMODA.png" },
  { name: "Jaecoo", logo: "https://www.wandaloo.com/imgs/logo-JAECOO.png" }
];
